name: Daily Scraper

on:
  schedule:
    - cron: "30 11 * * *"   # Se ejecuta todos los días a las 11:30 AM UTC
  workflow_dispatch:       # Permite ejecutar manualmente el workflow

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: |
          python scraper.py

      - name: Commit and push CSV
        env:
          PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global user.email "mirarraza@gmail.com"
          git config --global user.name "mirarraza"
          git add valores_cuota.csv
          git commit -m "Actualización diaria de valores" || echo "No hay cambios para commit"
          git remote set-url origin "https://$PAT_TOKEN@github.com/mirarraza/daily-scraper.git"
          git push origin HEAD:refs/heads/main || echo "Push falló, revisa la configuración"
